### ISSUE TITLE
Bug after installation

### ISSUE THREAD

**Issue by Sigri44** [AlexFlipnote/discord_bot.py#2]
Hi !

I have follow the tutorial, and when i lauch the py : 

```
File "index.py", line 25
    bot.load_extension(f"cogs.{name}")
                                    ^
SyntaxError: invalid syntax
```

Thx

**Comment by AlexFlipnote** [comment]
Check your python version by typing in CMD/Terminal:
`python -V`
![Image](https://i.alexflipnote.xyz/8fbf0b.png)

It must be 3.6 or above

**Comment by Sigri44** [comment]
Python 2.7.3 on linux2 ;(

**Comment by AlexFlipnote** [comment]
Sadly you are required to have 3.6 or above to use it.

**Comment by Sigri44** [comment]
I don't, i have always a bot for Discord, he don't support py >3.X.. :(

**Comment by AlexFlipnote** [comment]
Well, I'll close this for now, as you only need to upgrade python to get it.
