### ISSUE TITLE
Music Related command not working

### ISSUE THREAD

**Issue by Zet4Dragon** [AlexFlipnote/discord_bot.py#3]
The command playing gets this error.
![image](https://user-images.githubusercontent.com/26089350/34720934-9a338248-f538-11e7-9e40-5ed4e8c47b74.png)
Unfortunately, this is all I could trace.
The code doesn't seem to have problems as far as I can tell. Will continue to investigate.

**Comment by AlexFlipnote** [comment]
Which radio are you playing from?

**Comment by Zet4Dragon** [comment]
None of the stations displays the current track.

**Comment by AlexFlipnote** [comment]
I just tested with a 100% copy of the GitHub Source, works perfectly fine
![Image](https://i.alexflipnote.xyz/113e29.png)
