### ISSUE TITLE
I followed all the steps when I I try to run the bot it says : 

### ISSUE THREAD

**Issue by emptixo** [AlexFlipnote/discord_bot.py#4]
Python index.py
Traceback (most recent call last):
  File "index.py", line 5, in <module>
    from data import Bot
  File "/data/data/com.termux/files/home/data.py", line 2, in <module>
    from discord.ext.commands import AutoShardedBot
ImportError: cannot import name 'AutoShardedBot'
$

**Comment by AlexFlipnote** [comment]
![Preview](https://i.alexflipnote.xyz/da2a0d.png)

I tested a clean version of the bot and it works fine.
Are you sure you've installed Discord.py rewrite version?

**Comment by emptixo** [comment]
Yea I'm pretty sure m8, I double checked that !

**Comment by emptixo** [comment]
🤔

**Comment by AlexFlipnote** [comment]
Try to install discord.py again with this command:
```
pip install -U git+https://github.com/Rapptz/discord.py@rewrite --upgrade
```
because it works 100% fine with my bot

I did it myself just to be sure too

![Image](https://i.alexflipnote.xyz/f4566f.png)

and it worked just fine 

![Image2](https://i.alexflipnote.xyz/cd37b7.png)

**Comment by emptixo** [comment]
Alright, lemme try that !

**Comment by emptixo** [comment]
Ok, now I got this error : ```import psutil
ModuleNotFoundError: No module named 'psutil'``` I tried to install pustil with ```pip install pustil``` and i got this ```pip install pustil
Collecting pustil
  Could not find a version that satisfies the requirement pustil (from versions: )
No matching distribution found for pustil
$``` :/ 🤔🤔

**Comment by AlexFlipnote** [comment]
Should work fine to install it, make sure you're running on Python 3.6 or above 

![Image](https://i.alexflipnote.xyz/86576c.png)

**Comment by emptixo** [comment]
```pythonon python 3.6.4 latest version
Python 3.6.4 (default, Jan  7 2018, 03:53:53)
[GCC 4.2.1 Compatible Android Clang 5.0.300080 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>``` yes I'm running

**Comment by emptixo** [comment]
On latest version

**Comment by AlexFlipnote** [comment]
Ah, I see you're on Linux.
Read this page on how to install it.
You need to have Python Developer too

https://github.com/giampaolo/psutil/blob/master/INSTALL.rst

**Comment by emptixo** [comment]
Yoo

**Comment by emptixo** [comment]
THANKS MAN , THE BOT IS WORKING JUST FINE, ♥

**Comment by AlexFlipnote** [comment]
No problem, glad I could help ❤️

**Comment by DudeVoid** [comment]
yo nice
