### ISSUE TITLE
bot is not coming online

### ISSUE THREAD

**Issue by RAY-0001** [AlexFlipnote/discord_bot.py#45]
hi i did everything listed but the bot isn't coming online I did this on repl.it please respond soon

**Comment by AlexFlipnote** [comment]
Did you enable these two?
![image](https://user-images.githubusercontent.com/19587382/105971927-594ef700-608b-11eb-85d5-7deab45f44d4.png)

**Comment by RAY-0001** [comment]
yes i have but its still not coming online?

**Comment by AlexFlipnote** [comment]
Could you possibly provide any errors?

**Comment by RAY-0001** [comment]
sure 
![configjson](https://user-images.githubusercontent.com/77724132/105976489-248d7080-6088-11eb-817f-035db872152e.PNG)
![okay](https://user-images.githubusercontent.com/77724132/105976512-2a835180-6088-11eb-937e-530c6f215c33.PNG)

**Comment by RAY-0001** [comment]
![pip help](https://user-images.githubusercontent.com/77724132/105976707-6a4a3900-6088-11eb-980d-9942cc1c5b17.PNG)

**Comment by AlexFlipnote** [comment]
Read the README more clear, also I recommend renewing your token, since you leaked it now.

**Comment by 1chiSensei** [comment]
just do `pip install -U -r requirements.txt` lmfao in the console

**Comment by AlexFlipnote** [comment]
I won't support repl.it questions anymore
