### ISSUE TITLE
components/stream/worker.py (ERROR)

### ISSUE THREAD

**Issue by mbaveit** [AlexFlipnote/discord_bot.py#49]
HI,
I get thousands of errors in the log: 
Error parsing AU headers
11:08:11 – components/stream/worker.py (ERROR) - il messaggio si è verificato per la prima volta alle 10:08:45 e compare 6388 volte
Error parsing AU headers (repeated 12 more times)
11:08:11 – components/stream/worker.py (ERROR) - il messaggio si è verificato per la prima volta alle 10:08:44 e compare 4300 volte

This causes the log  fill up for several gb until homeassistant  freeze in 2/3 days.

**Comment by AlexFlipnote** [comment]
This has nothing to do with the project...
