### ISSUE TITLE
[QUESTION]Whats up with the api tokens?

### ISSUE THREAD

**Issue by Motzumoto** [AlexFlipnote/discord_bot.py#52]
Whats the point with having api tokens if you provide no documentation for them? And isnt this repo supposed to be for new coming users to dpy? i dont think having to find your api docs to use your dog / cat / etc commands is nice to have for new people.

**Comment by AlexFlipnote** [comment]
Hi there, I fully agree that it's a bit hypocritical of me to add that in the bot and expect people to find a way to make it work. These commands were added to the bot **before** my API had a token requirement and I simply forgot to remove it after I implemented it. Regardless, I improved it and pushed a better version at 1c6c67d and hope that resolves it.
