### ISSUE TITLE
= {       'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',       'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',       'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X',       'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f',       'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',       'o', 'p', 'q', 'r', 's', 't', 'u', 'v',       'w', 'x', 'y', 'z', '0', '1', '2', '3',       '4', '5', '6', '7', '8', '9', '+', '/'     };

### ISSUE THREAD

**Issue by tomjack76** [AlexFlipnote/discord_bot.py#68]
= {
      'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
      'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
      'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X',
      'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f',
      'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
      'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
      'w', 'x', 'y', 'z', '0', '1', '2', '3',
      '4', '5', '6', '7', '8', '9', '+', '/'
    };

**Comment by AlexFlipnote** [comment]
what even...

**Comment by DaInfLoop** [comment]
what the hell
