### ISSUE TITLE
Api Version 

### ISSUE THREAD

**Issue by Motzumoto** [AlexFlipnote/discord_bot.py#69]
```py
AttributeError: module 'discord.http' has no attribute 'API_VERSION'
```

**Comment by AlexFlipnote** [comment]
This was recently removed from the code due to the official discord.py project does not have such variable. I recommend updating your local project to the latest version of discord_bot.py

**Comment by AlexFlipnote** [comment]
Also #69, nice

**Comment by Motzumoto** [comment]
> Also #69, nice

haha, nice
