### ISSUE TITLE
discord.ext.commands.errors.CommandNotFound

### ISSUE THREAD

**Issue by 9z8** [AlexFlipnote/discord_bot.py#73]
<img width="520" alt="image" src="https://user-images.githubusercontent.com/76000462/172512775-337b2666-b945-4140-84ac-d25532c19086.png">
only the help command is working and it gives this 
`​No Category:
  help Shows this message

Type shelp command for more info on a command.
You can also type shelp category for more info on a category.
`

**Comment by XetPy1030** [comment]
try command: pip install -r requirements.txt

**Comment by AlexFlipnote** [comment]
You haven't added any commands to the bot
