### ISSUE TITLE
unclosed aiohttp clientSession

### ISSUE THREAD

**Issue by tiudvek** [AlexFlipnote/discord_bot.py#75]
Im using your aiohttp code, and every time i close my bot it tells me that `close()` needs to be await it, but when i make it an async function it just doesnt get ran, how do i fix it or could you?

**Comment by AlexFlipnote** [comment]
Think I never really paid too much attention to that and just let it stay since it only happened during shutdown of the bot. Could look more into it when I get time, no ETA on that however.

**Comment by tiudvek** [comment]
ight thx

**Comment by AlexFlipnote** [comment]
This has been resolved in the redesign, thank you for waiting!

**Comment by tiudvek** [comment]
thanks
